spring:
  application:
    name: NeoKG-backend
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/NeoKG
    username: NeoKG
    password: NeoKG
    driver-class-name: org.postgresql.Driver