spring:
  application:
    name: NeoKG-backend
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/NeoKG
    username: NeoKG
    password: NeoKG
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  ai:
    dashscope:
      chat:
        api-key: ${BAILIAN_KEY}
        options:
          model: qwen3-max-preview
      embedding:
        api-key: ${BAILIAN_KEY}
        options:
          model: text-embedding-v4
      api-key: ${BAILIAN_KEY}
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j123
  data:
    redis:
      port: 6379
      host: localhost

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




